load("@bazel_skylib//rules:native_binary.bzl", "native_binary")
load("@aspect_rules_lint//lint:clang_tidy.bzl", "clang_tidy_hint")

native_binary(
    name = "clang_tidy",
    src = "@llvm_toolchain_llvm//:clang-tidy",
    out = "clang_tidy",
)

filegroup(
    name = "clang_tidy_config",
    srcs = ["clang_tidy.toml"]
)

clang_tidy_hint(
    name = "ignore_headers",
    command_line_args = ["--header-filter="],
    visibility = ["//visibility:public"]
)
